### ISSUE TITLE
ptex-bind: please add @gsakura as a maintainer

### ISSUE THREAD

**Issue by davvid** [vfx-rs/ptex-bind#3]
Hi @scott-wilson

Please add @gsakura as a maintainer to this repository.

I'd like to add him as a reviewer on https://github.com/vfx-rs/ptex-bind/pull/2 but the github UI didn't let me add him. Feel free to reach out to me on the ASWF slack or email if you have any private questions.

cheers!

**Comment by scott-wilson** [comment]
I'll do you one better. I'll make sure you're an admin for this repo. Give me an hour or so. Just have a few things to do today.

**Comment by scott-wilson** [comment]
@davvid you should have permission to add them as a maintainer. I think you should be able to add them to the @vfx-rs/ptex-maintainers group. If not, I'll see what else needs to happen to give you permissions for that.

**Comment by davvid** [comment]
I was able to add Garret to the project directly but unfortunately I was not able to add him to the ptex-maintainers group (not sure why ~ probably more permissions I imagine).

This is good enough for me, but let me know if there's something else we should do to get him added to the team instead. Adding him to the team does seem preferable.

Thanks @scott-wilson!
